"""
Catalogue de ports proposés par défaut dans l'application, avec leurs
coordonnées géographiques (nécessaires à pyTMD et au calcul du crépuscule
nautique). La liste complète des sites d'api-maree.fr (GET /sites) y figure ; on n'est pas limité à ces noms :
`precompute.py --lat --lon --name` permet d'ajouter n'importe quel point.

Coordonnées approximatives (sortie de port / mouillage habituel), à
ajuster si besoin pour coller précisément à un spot de plongée donné.

offset_zh_m
-----------
Hauteur du niveau moyen (NM) au-dessus du zéro hydrographique (zéro des
cartes marines), en mètres. Elle est ajoutée aux hauteurs du modèle FES
(exprimées par rapport au niveau moyen) pour obtenir des hauteurs comme
dans l'annuaire SHOM.

Source officielle : colonne « NM » des Références Altimétriques Maritimes
(RAM) du Shom, sur data.shom.fr ou diffusion.shom.fr.

Tant qu'une valeur vaut 0, precompute.py refuse de traiter ce port
(sauf si --offset-zh est passé en ligne de commande).
"""

PORTS = [
    {"name": "Binic", "latitude": 48.6017, "longitude": -2.8244, "offset_zh_m": 6.68, "api_maree_site": "binic"},
    {"name": "Saint-Quay-Portrieux", "latitude": 48.6497, "longitude": -2.8419, "offset_zh_m": 6.57, "api_maree_site": "saint-quay-portrieux"},
    {"name": "Erquy", "latitude": 48.6386, "longitude": -2.4667, "offset_zh_m": 6.62, "api_maree_site": "erquy"},
    {"name": "Dahouet", "latitude": 48.5875, "longitude": -2.5875, "offset_zh_m": 0, "api_maree_site": "dahouet"},
    {"name": "Paimpol", "latitude": 48.7822, "longitude": -3.0367, "offset_zh_m": 6.25, "api_maree_site": "paimpol"},
    {"name": "Saint-Cast-le-Guildo", "latitude": 48.6386, "longitude": -2.2494, "offset_zh_m": 0, "api_maree_site": "saint-cast"},
    {"name": "Saint-Malo", "latitude": 48.6497, "longitude": -2.0256, "offset_zh_m": 0, "api_maree_site": "saint-malo"},
    {"name": "Perros-Guirec", "latitude": 48.8117, "longitude": -3.4425, "offset_zh_m": 0, "api_maree_site": "perros-guirec"},
    {"name": "Brest", "latitude": 48.3833, "longitude": -4.4931, "offset_zh_m": 4.32, "api_maree_site": "brest"},
    {"name": "Camaret-sur-Mer", "latitude": 48.2725, "longitude": -4.5936, "offset_zh_m": 0, "api_maree_site": "camaret-sur-mer"},
    {"name": "Douarnenez", "latitude": 48.0928, "longitude": -4.3286, "offset_zh_m": 0, "api_maree_site": "douarnenez"},
    {"name": "Concarneau", "latitude": 47.8742, "longitude": -3.9147, "offset_zh_m": 0, "api_maree_site": "concarneau"},
    {"name": "Lorient", "latitude": 47.7481, "longitude": -3.3661, "offset_zh_m": 0, "api_maree_site": "lorient"},
    {"name": "La Trinité-sur-Mer", "latitude": 47.5808, "longitude": -3.0169, "offset_zh_m": 0, "api_maree_site": "la-trinite-sur-mer"},
    {"name": "Quiberon (Port-Maria)", "latitude": 47.4808, "longitude": -3.1197, "offset_zh_m": 0, "api_maree_site": "quiberon-port-maria"},
    # Autres sites d'api-maree.fr (GET /sites), coordonnées de la station : à ajuster à l'eau avant le calcul
    {"name": "Aber Wrac'h", "latitude": 48.6119, "longitude": -4.5875, "offset_zh_m": 0, "api_maree_site": "aber-wrac-h"},
    {"name": "Anse de Primel", "latitude": 48.7211, "longitude": -3.8216, "offset_zh_m": 0, "api_maree_site": "anse-de-primel"},
    {"name": "Arcachon (Jetée d'Eyrac)", "latitude": 44.6661, "longitude": -1.1784, "offset_zh_m": 0, "api_maree_site": "arcachon-jetee-d-eyrac"},
    {"name": "Arradon", "latitude": 47.6172, "longitude": -2.8169, "offset_zh_m": 0, "api_maree_site": "arradon"},
    {"name": "Arromanches-les-Bains", "latitude": 49.3497, "longitude": -0.6176, "offset_zh_m": 0, "api_maree_site": "arromanches-les-bains"},
    {"name": "Audierne", "latitude": 48.0059, "longitude": -4.5336, "offset_zh_m": 0, "api_maree_site": "audierne"},
    {"name": "Auray (St-Goustan)", "latitude": 47.6014, "longitude": -2.9526, "offset_zh_m": 0, "api_maree_site": "auray-st-goustan"},
    {"name": "Baie de Morlaix - Carantec", "latitude": 48.6828, "longitude": -3.8991, "offset_zh_m": 0, "api_maree_site": "baie-de-morlaix-carantec"},
    {"name": "Baie de Saint-Brieuc (Le Légué)", "latitude": 48.5791, "longitude": -2.7469, "offset_zh_m": 0, "api_maree_site": "baie-de-saint-brieuc-le-legue"},
    {"name": "Barfleur", "latitude": 49.6989, "longitude": -1.2678, "offset_zh_m": 0, "api_maree_site": "barfleur"},
    {"name": "Belle-Île (Le Palais)", "latitude": 47.3496, "longitude": -3.1511, "offset_zh_m": 0, "api_maree_site": "belle-ile-le-palais"},
    {"name": "Berck Plage - Fort Mahon", "latitude": 50.3492, "longitude": 1.5165, "offset_zh_m": 0, "api_maree_site": "berck-plage-fort-mahon"},
    {"name": "Biscarrosse", "latitude": 44.3664, "longitude": -1.384, "offset_zh_m": 0, "api_maree_site": "biscarrosse"},
    {"name": "Bordeaux", "latitude": 45.0512, "longitude": -0.6204, "offset_zh_m": 0, "api_maree_site": "bordeaux"},
    {"name": "Boucau-Bayonne / Biarritz", "latitude": 43.528, "longitude": -1.5423, "offset_zh_m": 0, "api_maree_site": "boucau-bayonne-biarritz"},
    {"name": "Boulogne-sur-Mer", "latitude": 50.7347, "longitude": 1.5805, "offset_zh_m": 0, "api_maree_site": "boulogne-sur-mer"},
    {"name": "Brignogan-Plage", "latitude": 48.6773, "longitude": -4.3214, "offset_zh_m": 0, "api_maree_site": "brignogan-plage"},
    {"name": "Bénodet", "latitude": 47.8504, "longitude": -4.1091, "offset_zh_m": 0, "api_maree_site": "benodet"},
    {"name": "Calais", "latitude": 50.976, "longitude": 1.8671, "offset_zh_m": 0, "api_maree_site": "calais"},
    {"name": "Cancale", "latitude": 48.7098, "longitude": -1.8675, "offset_zh_m": 0, "api_maree_site": "cancale"},
    {"name": "Cap Ferret", "latitude": 44.6323, "longitude": -1.2391, "offset_zh_m": 0, "api_maree_site": "cap-ferret"},
    {"name": "Carteret", "latitude": 49.3323, "longitude": -1.8457, "offset_zh_m": 0, "api_maree_site": "carteret"},
    {"name": "Cayeux-sur-mer", "latitude": 50.1888, "longitude": 1.4714, "offset_zh_m": 0, "api_maree_site": "cayeux-sur-mer"},
    {"name": "Cherbourg", "latitude": 49.6493, "longitude": -1.6182, "offset_zh_m": 0, "api_maree_site": "cherbourg"},
    {"name": "Cordouan", "latitude": 45.5879, "longitude": -1.138, "offset_zh_m": 0, "api_maree_site": "cordouan"},
    {"name": "Courseulles-sur-Mer", "latitude": 49.3458, "longitude": -0.466, "offset_zh_m": 0, "api_maree_site": "courseulles-sur-mer"},
    {"name": "Dieppe", "latitude": 49.9343, "longitude": 1.0816, "offset_zh_m": 0, "api_maree_site": "dieppe"},
    {"name": "Dives-sur-Mer", "latitude": 49.3052, "longitude": -0.1052, "offset_zh_m": 0, "api_maree_site": "dives-sur-mer"},
    {"name": "Diélette", "latitude": 49.5524, "longitude": -1.8675, "offset_zh_m": 0, "api_maree_site": "dielette"},
    {"name": "Dunkerque", "latitude": 51.1449, "longitude": 2.3078, "offset_zh_m": 0, "api_maree_site": "dunkerque"},
    {"name": "Fouesnant", "latitude": 47.854, "longitude": -3.9662, "offset_zh_m": 0, "api_maree_site": "fouesnant"},
    {"name": "Fromentine", "latitude": 46.8886, "longitude": -2.1783, "offset_zh_m": 0, "api_maree_site": "fromentine"},
    {"name": "Fécamp", "latitude": 49.756, "longitude": 0.3468, "offset_zh_m": 0, "api_maree_site": "fecamp"},
    {"name": "Goury", "latitude": 49.7169, "longitude": -1.9518, "offset_zh_m": 0, "api_maree_site": "goury"},
    {"name": "Grandcamp", "latitude": 49.4037, "longitude": -1.0488, "offset_zh_m": 0, "api_maree_site": "grandcamp"},
    {"name": "Granville", "latitude": 48.8134, "longitude": -1.8979, "offset_zh_m": 0, "api_maree_site": "granville"},
    {"name": "Gravelines", "latitude": 51.107, "longitude": 2.051, "offset_zh_m": 0, "api_maree_site": "gravelines"},
    {"name": "Honfleur", "latitude": 49.4292, "longitude": 0.2319, "offset_zh_m": 0, "api_maree_site": "honfleur"},
    {"name": "Houat", "latitude": 47.3833, "longitude": -2.9493, "offset_zh_m": 0, "api_maree_site": "houat"},
    {"name": "Hoëdic", "latitude": 47.3338, "longitude": -2.8665, "offset_zh_m": 0, "api_maree_site": "hoedic"},
    {"name": "L'Aber Benoît", "latitude": 48.5894, "longitude": -4.6347, "offset_zh_m": 0, "api_maree_site": "l-aber-benoit"},
    {"name": "L'Aber Ildut - Lanildut", "latitude": 48.47, "longitude": -4.7661, "offset_zh_m": 0, "api_maree_site": "l-aber-ildut-lanildut"},
    {"name": "La Rochelle-Pallice", "latitude": 46.1671, "longitude": -1.2256, "offset_zh_m": 0, "api_maree_site": "la-rochelle-pallice"},
    {"name": "Lacanau", "latitude": 44.9659, "longitude": -1.3334, "offset_zh_m": 0, "api_maree_site": "lacanau"},
    {"name": "Le Conquet", "latitude": 48.3686, "longitude": -4.783, "offset_zh_m": 0, "api_maree_site": "le-conquet"},
    {"name": "Le Croisic", "latitude": 47.3091, "longitude": -2.529, "offset_zh_m": 0, "api_maree_site": "le-croisic"},
    {"name": "Le Guilvinec", "latitude": 47.7918, "longitude": -4.2877, "offset_zh_m": 0, "api_maree_site": "le-guilvinec"},
    {"name": "Le Havre", "latitude": 49.4788, "longitude": 0.0971, "offset_zh_m": 0, "api_maree_site": "le-havre"},
    {"name": "Le Havre-Antifer", "latitude": 49.666, "longitude": 0.151, "offset_zh_m": 0, "api_maree_site": "le-havre-antifer"},
    {"name": "Le Logeo", "latitude": 47.5452, "longitude": -2.8037, "offset_zh_m": 0, "api_maree_site": "le-logeo"},
    {"name": "Le Pouldu", "latitude": 47.7644, "longitude": -3.5371, "offset_zh_m": 0, "api_maree_site": "le-pouldu"},
    {"name": "Le Pouliguen", "latitude": 47.2574, "longitude": -2.4331, "offset_zh_m": 0, "api_maree_site": "le-pouliguen"},
    {"name": "Le Tréport", "latitude": 50.0898, "longitude": 1.0973, "offset_zh_m": 0, "api_maree_site": "le-treport"},
    {"name": "Les Héaux de Bréhat", "latitude": 48.8965, "longitude": -3.0926, "offset_zh_m": 0, "api_maree_site": "les-heaux-de-brehat"},
    {"name": "Les Sables-d'Olonne", "latitude": 46.4894, "longitude": -1.7883, "offset_zh_m": 0, "api_maree_site": "les-sables-d-olonne"},
    {"name": "Lesconil", "latitude": 47.791, "longitude": -4.2134, "offset_zh_m": 0, "api_maree_site": "lesconil"},
    {"name": "Locmariaquer", "latitude": 47.5719, "longitude": -2.9285, "offset_zh_m": 0, "api_maree_site": "locmariaquer"},
    {"name": "Locquemeau", "latitude": 48.7323, "longitude": -3.5824, "offset_zh_m": 0, "api_maree_site": "locquemeau"},
    {"name": "Locquirec", "latitude": 48.6918, "longitude": -3.6363, "offset_zh_m": 0, "api_maree_site": "locquirec"},
    {"name": "Loctudy", "latitude": 47.8392, "longitude": -4.1568, "offset_zh_m": 0, "api_maree_site": "loctudy"},
    {"name": "Luc-sur-mer", "latitude": 49.3451, "longitude": -0.3522, "offset_zh_m": 0, "api_maree_site": "luc-sur-mer"},
    {"name": "Mimizan", "latitude": 44.132, "longitude": -1.3503, "offset_zh_m": 0, "api_maree_site": "mimizan"},
    {"name": "Morgat", "latitude": 48.2144, "longitude": -4.4943, "offset_zh_m": 0, "api_maree_site": "morgat"},
    {"name": "Noirmoutier (L'Herbaudière)", "latitude": 47.0392, "longitude": -2.3371, "offset_zh_m": 0, "api_maree_site": "noirmoutier-l-herbaudiere"},
    {"name": "Omonville-la-Rogue", "latitude": 49.7169, "longitude": -1.8338, "offset_zh_m": 0, "api_maree_site": "omonville-la-rogue"},
    {"name": "Ouistreham", "latitude": 49.3327, "longitude": -0.2513, "offset_zh_m": 0, "api_maree_site": "ouistreham"},
    {"name": "Pauillac", "latitude": 45.2157, "longitude": -0.7244, "offset_zh_m": 0, "api_maree_site": "pauillac"},
    {"name": "Penfret (Îles de Glénan)", "latitude": 47.7332, "longitude": -3.9508, "offset_zh_m": 0, "api_maree_site": "penfret-iles-de-glenan"},
    {"name": "Penmarc'h / Saint-Guénolé", "latitude": 47.8176, "longitude": -4.3849, "offset_zh_m": 0, "api_maree_site": "penmarc-h-saint-guenole"},
    {"name": "Ploumanac'h", "latitude": 48.8382, "longitude": -3.4847, "offset_zh_m": 0, "api_maree_site": "ploumanac-h"},
    {"name": "Pointe d'Agon", "latitude": 49.0154, "longitude": -1.7798, "offset_zh_m": 0, "api_maree_site": "pointe-d-agon"},
    {"name": "Pointe de Gatseau", "latitude": 45.7547, "longitude": -1.2829, "offset_zh_m": 0, "api_maree_site": "pointe-de-gatseau"},
    {"name": "Pointe de Grave (Port-Bloc)", "latitude": 45.5934, "longitude": -1.0643, "offset_zh_m": 0, "api_maree_site": "pointe-de-grave-port-bloc"},
    {"name": "Pointe de Saint-Gildas", "latitude": 47.1292, "longitude": -2.2345, "offset_zh_m": 0, "api_maree_site": "pointe-de-saint-gildas"},
    {"name": "Pornic", "latitude": 47.1045, "longitude": -2.0988, "offset_zh_m": 0, "api_maree_site": "pornic"},
    {"name": "Pornichet", "latitude": 47.2506, "longitude": -2.3503, "offset_zh_m": 0, "api_maree_site": "pornichet"},
    {"name": "Port du Crouesty", "latitude": 47.5317, "longitude": -2.8996, "offset_zh_m": 0, "api_maree_site": "port-du-crouesty"},
    {"name": "Port Manec'h", "latitude": 47.7993, "longitude": -3.7335, "offset_zh_m": 0, "api_maree_site": "port-manec-h"},
    {"name": "Port-Béni", "latitude": 48.818, "longitude": -3.2017, "offset_zh_m": 0, "api_maree_site": "port-beni"},
    {"name": "Port-en-Bessin", "latitude": 49.3526, "longitude": -0.7492, "offset_zh_m": 0, "api_maree_site": "port-en-bessin"},
    {"name": "Port-Louis (Locmalo)", "latitude": 47.7206, "longitude": -3.3563, "offset_zh_m": 0, "api_maree_site": "port-louis-locmalo"},
    {"name": "Port-Navalo", "latitude": 47.5497, "longitude": -2.9162, "offset_zh_m": 0, "api_maree_site": "port-navalo"},
    {"name": "Portbail", "latitude": 49.3281, "longitude": -1.7406, "offset_zh_m": 0, "api_maree_site": "portbail"},
    {"name": "Portsall", "latitude": 48.5714, "longitude": -4.7055, "offset_zh_m": 0, "api_maree_site": "portsall"},
    {"name": "Pénerf", "latitude": 47.5002, "longitude": -2.6316, "offset_zh_m": 0, "api_maree_site": "penerf"},
    {"name": "Quiberon (Port-Haliguen)", "latitude": 47.4845, "longitude": -3.0949, "offset_zh_m": 0, "api_maree_site": "quiberon-port-haliguen"},
    {"name": "Quinéville", "latitude": 49.5185, "longitude": -1.2651, "offset_zh_m": 0, "api_maree_site": "quineville"},
    {"name": "Richards", "latitude": 45.4702, "longitude": -0.9015, "offset_zh_m": 0, "api_maree_site": "richards"},
    {"name": "Roscoff", "latitude": 48.7323, "longitude": -3.9968, "offset_zh_m": 0, "api_maree_site": "roscoff"},
    {"name": "Royan", "latitude": 45.6044, "longitude": -1.0519, "offset_zh_m": 0, "api_maree_site": "royan"},
    {"name": "Saint-Germain-sur-Ay", "latitude": 49.23, "longitude": -1.6613, "offset_zh_m": 0, "api_maree_site": "saint-germain-sur-ay"},
    {"name": "Saint-Gilles-Croix-de-Vie", "latitude": 46.6922, "longitude": -1.9501, "offset_zh_m": 0, "api_maree_site": "saint-gilles-croix-de-vie"},
    {"name": "Saint-Jean-de-Luz", "latitude": 43.4075, "longitude": -1.6919, "offset_zh_m": 0, "api_maree_site": "saint-jean-de-luz"},
    {"name": "Saint-Nazaire", "latitude": 47.2664, "longitude": -2.2014, "offset_zh_m": 0, "api_maree_site": "saint-nazaire"},
    {"name": "Saint-Vaast-la-Hougue", "latitude": 49.5797, "longitude": -1.2694, "offset_zh_m": 0, "api_maree_site": "saint-vaast-la-hougue"},
    {"name": "Saint-Valery-en-Caux", "latitude": 49.8757, "longitude": 0.7174, "offset_zh_m": 0, "api_maree_site": "saint-valery-en-caux"},
    {"name": "Sainte-Marie-du-Mont (Utah Beach)", "latitude": 49.4525, "longitude": -1.1875, "offset_zh_m": 0, "api_maree_site": "sainte-marie-du-mont-utah-beach"},
    {"name": "Surtainville", "latitude": 49.451, "longitude": -1.8481, "offset_zh_m": 0, "api_maree_site": "surtainville"},
    {"name": "Trez-Hir", "latitude": 48.3393, "longitude": -4.6414, "offset_zh_m": 0, "api_maree_site": "trez-hir"},
    {"name": "Trouville / Deauville", "latitude": 49.3706, "longitude": 0.0667, "offset_zh_m": 0, "api_maree_site": "trouville-deauville"},
    {"name": "Trébeurden", "latitude": 48.7571, "longitude": -3.5656, "offset_zh_m": 0, "api_maree_site": "trebeurden"},
    {"name": "Trégastel", "latitude": 48.8382, "longitude": -3.5386, "offset_zh_m": 0, "api_maree_site": "tregastel"},
    {"name": "Tréguier", "latitude": 48.8157, "longitude": -3.2017, "offset_zh_m": 0, "api_maree_site": "treguier"},
    {"name": "Tréhiguier", "latitude": 47.507, "longitude": -2.4761, "offset_zh_m": 0, "api_maree_site": "trehiguier"},
    {"name": "Vannes", "latitude": 47.6082, "longitude": -2.7507, "offset_zh_m": 0, "api_maree_site": "vannes"},
    {"name": "Vauville", "latitude": 49.6296, "longitude": -1.8611, "offset_zh_m": 0, "api_maree_site": "vauville"},
    {"name": "Vierville", "latitude": 49.3864, "longitude": -0.9043, "offset_zh_m": 0, "api_maree_site": "vierville"},
    {"name": "Vieux-Boucau", "latitude": 43.7782, "longitude": -1.421, "offset_zh_m": 0, "api_maree_site": "vieux-boucau"},
    {"name": "Wissant", "latitude": 50.8948, "longitude": 1.6615, "offset_zh_m": 0, "api_maree_site": "wissant"},
    {"name": "Étel", "latitude": 47.6261, "longitude": -3.2239, "offset_zh_m": 0, "api_maree_site": "etel"},
    {"name": "Étretat", "latitude": 49.7178, "longitude": 0.2016, "offset_zh_m": 0, "api_maree_site": "etretat"},
    {"name": "Île d'Oléron (La Cotinière)", "latitude": 45.9057, "longitude": -1.3536, "offset_zh_m": 0, "api_maree_site": "ile-d-oleron-la-cotiniere"},
    {"name": "Île d'Yeu", "latitude": 46.7851, "longitude": -2.4066, "offset_zh_m": 0, "api_maree_site": "ile-d-yeu"},
    {"name": "Île de Groix (Port-Tudy)", "latitude": 47.6509, "longitude": -3.4489, "offset_zh_m": 0, "api_maree_site": "ile-de-groix-port-tudy"},
    {"name": "Île de Ré (Saint-Martin)", "latitude": 46.2685, "longitude": -1.3671, "offset_zh_m": 0, "api_maree_site": "ile-de-re-saint-martin"},
    {"name": "Île des Ébihens", "latitude": 48.6174, "longitude": -2.1404, "offset_zh_m": 0, "api_maree_site": "ile-des-ebihens"},
    {"name": "Île-Grande", "latitude": 48.8158, "longitude": -3.5988, "offset_zh_m": 0, "api_maree_site": "ile-grande"},
    {"name": "Îles Saint-Marcouf", "latitude": 49.5006, "longitude": -1.1331, "offset_zh_m": 0, "api_maree_site": "iles-saint-marcouf"},
]
